language: python

python: 3.6

env:
  - TOX_ENV=py36-django111
  - TOX_ENV=py35-django111
  - TOX_ENV=py34-django111
  - TOX_ENV=py27-django111
  - TOX_ENV=py35-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py27-django110
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py27-django18
  - TOX_ENV=flake8
  - TOX_ENV=docs

install: pip install tox

script: tox -e $TOX_ENV
