language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
  matrix:
    - TOX_ENV=py34-django17
    - TOX_ENV=py33-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=py33-django16
    - TOX_ENV=py27-django16
    - TOX_ENV=py26-django16
    - TOX_ENV=py27-django14
    - TOX_ENV=py26-django14
    - TOX_ENV=flake8
    - TOX_ENV=docs
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
